export const FAQS = [
  {
    question: "What is Decko?",
    answer: "Decko is an AI-powered presentation planner and outline generator. It drafts fully structured, professional chapter guides, outlines, and summaries for your topics in seconds, helping you skip the dreaded blank-slide phase of creating presentations.",
  },
  {
    question: "How does the credit system work?",
    answer: "Every registered user starts with 2 free credits. You can generate outlines using different AI models which deduct credits based on their capability: Owl Alpha (1 credit/run), DeepSeek V4 (3 credits/run), or GPT-5.5 (7 credits/run). Refills and extra credit packs can be purchased at any time.",
  },
  {
    question: "Are presentation revisions free?",
    answer: "Yes! Once you generate an outline, you can interactively revise, update, or expand it using our natural chat pane up to 3 times per presentation. Revisions are completely free and consume zero extra credits.",
  },
  {
    question: "Can I export my outlines?",
    answer: "Absolutely. You can export any generated presentation outline directly into structured PDF documents or styled Microsoft Word (.docx) formats with a single click, ready to share or import into presentation software.",
  },
  {
    question: "Is there a limit on how many outlines I can save?",
    answer: "No. Your generated presentation outline history is securely saved in your personal sidebar workspace so you can access, edit, revise, or re-export them whenever you need.",
  },
];

export const PRICING_PLANS = [
  {
    name: "Free Trial",
    price: "$0",
    priceSub: "starter",
    tagline: "Test the waters",
    description: "Get a taste of automated presentation planning with our basic model.",
    credits: "2 Credits",
    chapterLimit: "Up to 5 Chapters / outline",
    modelAccess: "Owl Alpha (Fast)",
    features: [
      "2 free credits immediately",
      "Fast basic generation (Owl Alpha)",
      "Up to 5 chapters per presentation",
      "3 free interactive revisions",
      "Standard PDF & Word exports",
    ],
    buttonText: "Get Started Free",
    actionLink: "/auth/signup",
    popular: false,
    creditRate: "Free signup reward",
  },
  {
    name: "Starter Pack",
    price: "$5",
    priceSub: "one-time",
    tagline: "Perfect for students & writers",
    description: "Generate longer, more comprehensive drafts with our advanced model.",
    credits: "10 Credits",
    chapterLimit: "Up to 10 Chapters / outline",
    modelAccess: "DeepSeek V4 + Owl Alpha",
    features: [
      "10 credits refilled instantly",
      "Access to DeepSeek V4 (3 credits/run)",
      "Up to 10 chapters per outline",
      "3 free interactive revisions",
      "Standard PDF & Word exports",
      "Priority outline generation speed",
    ],
    buttonText: "Get Starter Pack",
    actionLink: "/auth/login?purchase=starter",
    popular: false,
    creditRate: "$0.50 per credit",
  },
  {
    name: "Pro Pack",
    price: "$15",
    priceSub: "one-time",
    tagline: "For creators & professionals",
    description: "Unlock our highest-quality intelligence for complex and detailed outlines.",
    credits: "50 Credits",
    chapterLimit: "Up to 14 Chapters / outline",
    modelAccess: "GPT-5.5 + DeepSeek V4 + Owl Alpha",
    features: [
      "50 credits refilled instantly",
      "Access to GPT-5.5 (7 credits/run)",
      "Up to 14 chapters per outline",
      "3 free interactive revisions",
      "Premium formatted PDF & Word exports",
      "Ultra-fast processing speed",
      "Full priority support",
    ],
    buttonText: "Upgrade to Pro",
    actionLink: "/auth/login?purchase=pro",
    popular: true,
    creditRate: "$0.30 per credit",
    saving: "Save 40% vs Starter",
  },
];
